source 'https://rubygems.org'
ruby '2.1.3'

gem 'rake', '~> 10.3'
gem 'rspec', '~> 3.1'
gem 'sequel', '~> 4.16'
gem 'mysql2', '~> 0.3', '>= 0.3.16'
gem 'sinatra', '~> 1.4', '>= 1.4.5'
gem 'sinatra-sequel_extension', '~> 0.9', git: 'git://github.com/danascheider/sinatra-sequel_extension.git', require: 'sinatra/sequel'
gem 'thin', '~> 1.6.2'